import { CurrentUserObject, LimitedUserObject } from 'src/types/User'
import { WorldObject } from 'src/types/World'

export const CurrentUserTestData: CurrentUserObject = {
  acceptedTOSVersion: 0,
  accountDeletionDate: null,
  activeFriends: [],
  allowAvatarCopying: true,
  bio: '',
  bioLinks: [],
  currentAvatar: '',
  currentAvatarAssetUrl: '',
  currentAvatarImageUrl: '',
  currentAvatarThumbnailImageUrl: '',
  date_joined: '',
  developerType: 'none',
  displayName: '',
  email: '',
  emailVerified: true,
  fallbackAvatar: '',
  feature: { twoFactorAuth: false },
  friendGroupNames: [],
  friendKey: '',
  friends: [],
  hasBirthday: true,
  hasEmail: true,
  hasLoggedInFromClient: true,
  hasPendingEmail: true,
  homeLocation: '',
  id: '',
  isFriend: true,
  last_login: '',
  last_platform: '',
  obfuscatedEmail: '',
  obfuscatedPendingEmail: '',
  oculusId: '',
  offlineFriends: [],
  onlineFriends: [],
  pastDisplayNames: [],
  state: 'offline',
  status: 'active',
  statusDescription: '',
  steamDetails: null,
  steamId: '',
  tags: [],
  twoFactorAuthEnabled: true,
  unsubscribe: true,
  userIcon: '',
  username: ''
}

export const LimitedUserTestData: LimitedUserObject = {
  bio: 'undefined',
  currentAvatarImageUrl: '',
  currentAvatarThumbnailImageUrl: '',
  developerType: 'none',
  displayName: '',
  fallbackAvatar: '',
  friendKey: '',
  id: '',
  isFriend: true,
  last_login: '',
  last_platform: '',
  location: '',
  status: 'active',
  statusDescription: '',
  tags: [],
  userIcon: '',
  username: ''
}

export const WorldObjectTestData: WorldObject = {
  assetUrl: '',
  assetUrlObject: 'unknown',
  authorId: '',
  authorName: '',
  capacity: 0,
  created_at: '',
  description: '',
  favorites: 0,
  featured: true,
  heat: 0,
  id: '',
  imageUrl: '',
  instances: [],
  labsPublicationDate: '',
  name: '',
  namespace: '',
  occupants: 0,
  organization: '',
  pluginUrl: 'undefined',
  pluginUrlObject: 'unknown',
  popularity: 0,
  previewYoutubeId: 'unknown',
  privateOccupants: 0,
  publicOccupants: 0,
  publicationDate: '',
  releaseStatus: 'public',
  tags: [],
  thumbnailImageUrl: '',
  unityPackageUrl: 'undefined',
  unityPackageUrlObject: 'unknown',
  unityPackages: [],
  updated_at: '',
  version: 0,
  visits: 0
}
