name: jest coverage
on: [pull_request]

jobs:
  jest-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - uses: actions/checkout@v2
    - run: npm ci
    - uses: mattallty/jest-github-action@v1
    env:
      VRC_USERNAME: ${{ secrets.VRC_USERNAME }}
      VRC_PASSWORD: ${{ secrets.VRC_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
